config/routes.rb
require 'sidekiq/web'

PennyAuction::Application.routes.draw do

  root to: 'auctions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get 'profile', to: 'registrations#show'
    get 'profile/edit', to: 'registrations#edit'
  end

  resources :auctions, only: [:index, :show] do
    resources :bids, only: [:create]
  end

  namespace :admin do
    root to: 'site#index'

    resources :categories do
      resources :images
    end

    resources :products do
      resources :images
    end

    resources :auctions

    resources :users, only: [:index, :show, :new, :create, :edit, :update]

    resources :roles, only: [:index, :show] do
      resources :permissions, only: [:index, :create, :destroy]
    end

    get 'image-selector/:product_id', to: 'auctions#image_selector'

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/views/shared/_admin_links.html.slim
li= link_to t('admin.products.index.title'), admin_products_path
li= link_to t('admin.categories.index.title'), admin_categories_path
li= link_to t('admin.auctions.index.title'), admin_auctions_path
li= link_to t('admin.users.index.title'), admin_users_path if can?(:manage, User)
li= link_to t('admin.roles.index.title'), admin_roles_path if can?(:manage, Role)

app/views/shared/_flash.html.slim
= bootstrap_flash

app/views/shared/_footer.html.slim
footer
  = nav_bar :static => :bottom
    .footer-inner.text-center
      p &copy; Alex Emelyanov 2014

app/views/shared/_user_panel.html.slim
.user-nav
  - if user_signed_in?
    - if can? :read, :admin_panel
      - if request.path.starts_with?(admin_root_path)
        =' link_to t('helpers.links.user_mode'), root_path, class: 'btn btn-success'
      - else
        =' link_to t('helpers.links.admin_mode'), admin_root_path, class: 'btn btn-warning'
    =' link_to current_user.email, profile_path, class: 'btn btn-default'
    = link_to t('devise.buttons.signout'), destroy_user_session_path, method: :delete, class: 'btn btn-danger'
  - else
    =' link_to t('devise.buttons.signup'), new_user_registration_path, class: 'btn btn-primary'
    = link_to t('devise.buttons.signin'), new_user_session_path, class: 'btn btn-success'

app/views/shared/_validation_errors.html.slim
#error_explanation
  ul
    - model_class = resource.class
    - resource.errors.each do |attr, msg|
      - if resource.errors[attr].first == msg
        li class="alert alert-error" = "#{model_class.human_attribute_name(attr)} #{msg}"