config/routes.rb
require 'sidekiq/web'

PennyAuction::Application.routes.draw do

  root to: 'auctions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get 'profile', to: 'registrations#show'
    get 'profile/edit', to: 'registrations#edit'
  end

  resources :auctions, only: [:index, :show] do
    resources :bids, only: [:create]
  end

  namespace :admin do
    root to: 'site#index'

    resources :categories do
      resources :images
    end

    resources :products do
      resources :images
    end

    resources :auctions

    resources :users, only: [:index, :show, :new, :create, :edit, :update]

    resources :roles, only: [:index, :show] do
      resources :permissions, only: [:index, :create, :destroy]
    end

    get 'image-selector/:product_id', to: 'auctions#image_selector'

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :role_permissions
  has_many :permissions, through: :role_permissions

  validates :name, presence: true

  def self.default_role
    find_by name: 'user'
  end

  def self.bot
    find_by name: 'bot'
  end

  def self.admin
    find_by name: 'admin'
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
  respond_to :html, only: [:index, :show, :edit, :update]
end

app/views/admin/roles/index.html.slim
- model_class = Role
div.page-header
  h1 = t '.title'
table.table.table-striped
  thead.list-header
    tr
      th = model_class.human_attribute_name(:name)
      th
  tbody
    - @roles.each do |role|
      tr.list-item
        td = link_to role.name, [:admin, role]
        td = link_to t('helpers.links.edit'), admin_role_permissions_path(role), class: 'btn btn-mini'

app/views/admin/roles/show.html.slim
- model_class = Role
div.page-header
  h1 = @role.name

ul
  - @role.permissions.each do |permission|
    li = permission.name

.form-actions
  = link_to t('helpers.links.back'), admin_roles_path, class: 'btn'