config/routes.rb
require 'sidekiq/web'

PennyAuction::Application.routes.draw do

  root to: 'auctions#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  devise_scope :user do
    get 'profile', to: 'registrations#show'
    get 'profile/edit', to: 'registrations#edit'
  end

  resources :auctions, only: [:index, :show] do
    resources :bids, only: [:create]
  end

  namespace :admin do
    root to: 'site#index'

    resources :categories do
      resources :images
    end

    resources :products do
      resources :images
    end

    resources :auctions

    resources :users, only: [:index, :show, :new, :create, :edit, :update]

    resources :roles, only: [:index, :show] do
      resources :permissions, only: [:index, :create, :destroy]
    end

    get 'image-selector/:product_id', to: 'auctions#image_selector'

    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :images, as: :imageable

  validates :name, :description, :shop_price, :category, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validates :shop_price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :shop_price, fractionality: { multiplier: 0.01 }
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  respond_to :html  

  def show
    @imageable = resource
    @image = Image.new
  end

  def create
    create!(notice: t('activerecord.successful.messages.product_saved'))
  end

  def update
    update!(notice: t('activerecord.successful.messages.product_saved'))
  end

  private

  def build_resource_params
    [params.fetch(:product, {}).permit(:name, :description, :shop_price, :category_id)]
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @imageable = @product
    @image = Image.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :shop_price, :category_id)
    end
end

app/views/admin/products/_form.html.slim
= form_for [:admin, @product], html: { class: "form-horizontal" } do |f|
  = render 'shared/validation_errors', resource: @product
  .control-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'text_field'
  .control-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'text_field'
  .control-group
    = f.label :shop_price, class: 'control-label'
    .controls
      = f.text_field :shop_price, class: 'text_field'
  .control-group
    = f.label :category_id, class: 'control-label'
    .controls
      = f.collection_select :category_id, Category.order(:name), :id, :name, {}, class: 'selectpicker'

  .form-actions
    = f.submit t('helpers.links.save'), class: 'btn btn-primary'
    '
    = link_to t('helpers.links.cancel'), admin_products_path, class: 'btn'

app/views/admin/products/edit.html.slim
- model_class = Product
div class="page-header"
  h1 = t '.title'
= render partial: "form"

app/views/admin/products/images_selector.html.slim
= collection_radio_buttons :auction, :image_id, @product.images.order(:source), :id, :thumb_url, {checked: @auction && @auction.image_id}, class: 'selectpicker' do |image|
  = image.label do
    =' image.radio_button
    = image_tag(image.text)

app/views/admin/products/index.html.slim
- model_class = Product
div class="page-header"
  h1 = t '.title'
table class="table table-striped"
  thead
    tr.list-header
      th= model_class.human_attribute_name(:name)
      th= model_class.human_attribute_name(:description)
      th= model_class.human_attribute_name(:shop_price)
      th= model_class.human_attribute_name(:category_id)
      th
  tbody.list
    - @products.each do |product|
      tr.list-item
        td= link_to product.name, [:admin, product]
        td= product.description
        td= product.shop_price
        td= product.category.name
        td
          = link_to t('helpers.links.edit'), edit_admin_product_path(product), class: 'btn btn-mini'
          '
          = link_to t('helpers.links.destroy'), admin_product_path(product), method: :delete, data: { confirm: t('helpers.links.confirm') }, class: 'btn btn-mini btn-danger'

= link_to t('helpers.links.new'), new_admin_product_path, class: 'btn btn-primary'

app/views/admin/products/new.html.slim
- model_class = Product
div class="page-header"
  h1 = t '.title'
= render partial: "form"

app/views/admin/products/show.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', default: model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:name) + ':'
  br
  = @product.name
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @product.description
p
  strong= model_class.human_attribute_name(:shop_price) + ':'
  br
  = @product.shop_price
p
  strong= model_class.human_attribute_name(:category_id) + ':'
  br
  = @product.category.name
div.images
  - @product.images.each do |image|
    = image_tag image.thumb_url
    '
    = link_to t('.destroy', default: t("helpers.links.destroy")), [:admin, @product, image], method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'
    br
  = render "admin/images/form"
.form-actions
  = link_to t('.back', default: t("helpers.links.back")), admin_products_path, class: 'btn'
  '
  = link_to t('.edit', default: t("helpers.links.edit")), edit_admin_product_path(@product), class: 'btn'
  '
  = link_to t('.destroy', default: t("helpers.links.destroy")), admin_product_path(@product), method: "delete", data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) }, class: 'btn btn-danger'